version: '3.4'

services:
  ship-api:
    container_name: ship-api
    image: ${DOCKER_REGISTRY-}ship-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "7195:443"
      - "5260:80"
    depends_on:
      - db

  db:
    container_name: sql_server2022
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "S3cur3P@ssW0rd!"
        ACCEPT_EULA: "Y"

  ship-front:
    container_name: ship-front
    image: ${DOCKER_REGISTRY-}ship-front
    build:
      context: ./ship-front/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      
      
      